# Generated by Django 5.1.2 on 2024-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='conInvRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Untitled Project', max_length=100)),
                ('Email', models.CharField(default='Untitled Project', max_length=100)),
                ('Phone', models.IntegerField(max_length=100)),
                ('userName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StuRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuName', models.CharField(default='Untitled Project', max_length=100)),
                ('StuEmail', models.CharField(default='Untitled Project', max_length=100)),
                ('StuPhone', models.IntegerField(max_length=100)),
                ('userName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
