# Generated by Django 5.1.2 on 2024-11-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pitchIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='Untitled Project', max_length=100)),
                ('ideTitle', models.CharField(default='Untitled Project', max_length=100)),
                ('abstract', models.IntegerField()),
                ('IdeSynopsis', models.FileField(upload_to='uploads/synopsis')),
                ('stu_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sturegister',
            name='stu_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coninvregister',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sturegister',
            name='StuPhone',
            field=models.IntegerField(),
        ),
    ]
