# Generated by Django 5.1.2 on 2024-11-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pitchidea_sturegister_stu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchidea',
            name='abstract',
            field=models.CharField(default='Untitled Project', max_length=100),
        ),
    ]
