# Generated by Django 5.1.2 on 2024-11-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pitchidea_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='investorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investorName', models.CharField(default='Untitled Project', max_length=100)),
                ('domain', models.CharField(default='Untitled Project', max_length=100)),
                ('discription', models.CharField(default='Untitled Project', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemeName', models.CharField(default='Untitled Project', max_length=100)),
                ('schemeDetails', models.CharField(default='Untitled Project', max_length=100)),
                ('schemeLink', models.CharField(default='Untitled Project', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='coninvregister',
            name='role',
            field=models.CharField(default='Untitled Project', max_length=100),
        ),
        migrations.AddField(
            model_name='pitchidea',
            name='InvestorID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitchidea',
            name='description',
            field=models.CharField(default='Untitled Project', max_length=500),
        ),
        migrations.AddField(
            model_name='pitchidea',
            name='prjId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pitchidea',
            name='abstract',
            field=models.CharField(default='Untitled Project', max_length=500),
        ),
    ]
