# Generated by Django 5.1.2 on 2024-11-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_investorpost_schemes_coninvregister_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchidea',
            old_name='InvestorID',
            new_name='InvestorName',
        ),
    ]
