# Generated by Django 5.1.2 on 2024-11-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_investorid_pitchidea_investorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='schemeType',
            field=models.CharField(default='Untitled Project', max_length=100),
        ),
    ]
